sudo: false

language: scala

scala:
- 2.10.7
- 2.11.12
- 2.12.8
- 2.13.0

jdk:
- oraclejdk8

script:
 - sbt ++${TRAVIS_SCALA_VERSION} clean test

 # Avoid unnecessary cache updates
 - find $HOME/.sbt -name "*.lock" -delete
 - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
