sudo: false

language: scala

scala:
- 2.12.15
- 2.13.8

jdk:
- oraclejdk8

script:
 - sbt ++${TRAVIS_SCALA_VERSION} clean test

 # Avoid unnecessary cache updates
 - find $HOME/.sbt -name "*.lock" -delete
 - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
